### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by cjc7373** [NWU-MIS-2020/MIS-frontend#11]
- [x] 毕业要求的表格 css 是错的
- [x] 开设课程模块
- [x] 教师 选择班级 - 查看状态 - 录入界面
- [x] 导员查询达成度列表
- [x] 课程教学目标 （在支撑矩阵里修改
- [x] ~~历史课程的CURD （似乎在系统边界外？~~
- [ ] 指标点列表界面加统计图 （可以把学生模块的图复用一下
      所有学生毕业要求预测值的分布统计
- [x] ~~/prediction/student 接口返回的评价值总是null？（待调查~~
- [x] 整合导入excel
- [x] 修改评价值的名称
- [x] 学生模块还有一些问题
- [ ] 开设课程的 CU做成 selector
- [x] 假的导入
- [x] 专业负责人的统计
- [x] 达成度列表的筛选（查询指标点未达成学生名单那
- [x] 达成度列表 显示年级
- [x] 详细评价值的课程部分
- [x] 批量导入后更新审核状态
- [ ] 修改评价值界面显示评价值

**Comment by cjc7373** [comment]
已知bug
- 修改支撑矩阵后，课程名称会消失
- 指标点修改后没更新vuex 可能有未知bug
- 从达成度列表进入详细页面后 再点导航栏的详细页面 text-field 状态不会更新（可能需要路由守卫

**Comment by gongzhimin** [comment]
优先级由高到低：
- [x] pm：毕业要求及指标都点/支撑矩阵/开设课程的导入导出（导出的功能钧博在做
       暂时做了个真的假的
- [x] teacher：当历史课程处于未通过状态时，该信息标红
- [x] tutor：当某达成度小于0.65时标红处理
- [x] tutor：显示所管理班级的所属年级
- [x] tutor：统计功能
- [x] pm：统计功能
- [x] tutor：合并两项查询功能

**Comment by cjc7373** [comment]
🎉
